### ISSUE TITLE
Application Layout as React Component

### ISSUE THREAD

**Issue by timomeh** [railslove/rails-ssr-react-demo#14]
Maybe something similar to Next.js' custom app and custom document

https://nextjs.org/docs#custom-app
https://nextjs.org/docs#custom-document

**Comment by jhilden** [comment]
For me, this is relatively low priority and would be more of a cosmetic improvement.

**Comment by timomeh** [comment]
Pro:

- It would unify the underlying rendering logic. Currently we're building an html-string in javascript, passing it into ruby, splitting this string into head and body, storing the `ssr_head` as attribute in the controller, printing it in `application.html.erb`. Instead all of this could happen inside JS in a single react tree.
- Wrapping the whole component tree inside one or more `<Providers />` is a common pattern in many libraries. We already use it for react-helmet: https://github.com/railslove/rails-ssr-react-demo/blob/f2dbe694aa489b9d2c37e3cea1ed826240e843d4/app/javascript/packs/application.js#L53-L57

Con:

- The JS Application Layout wouldn't work with erb views, which means you need two layouts if you use React views in addition to erb views (e.g. when incrementally moving to react views).

---

I find the separation of the terms "app" and "document" interesting.

The "custom app" would be useful for wrapping views in providers (see above), but the "custom document" (which is the layout in rails) wouldn't be beneficial as react component. 

create-react-app also has no "custom document" as react component, it's just a simple html file.

**Comment by jhilden** [comment]
I definitely see the need for wrapping views in providers.  But maybe Helmet is not the best example, as it is tied to the logic of the renderer. I expect that other providers could be much simpler.
